default_config:
lovelace:
  # mode: yaml
  resources:
    - url: http://127.0.0.1:5000/fluid-level-background-card.js
      type: module

input_number:
  battery_level:
    name: Battery Level
    initial: 20
    min: 0
    max: 100
    step: .5
    icon: hass:battery
  
  energy_consumption:
    name: Today's Energy Consumption
    initial: 0.95
    min: 0
    max: 2.0
    step: 0.01
    unit_of_measurement: "kWh"
    icon: mdi:lightning-bolt

input_boolean:
  battery_charging:
    name: Battery charging
#demo:

