#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt

sudo apt-get update
sudo apt-get install ffmpeg -y
sudo apt-get install nodejs -y
sudo apt-get install npm -y

npm i --legacy-peer-deps
